update bridgeExporter to hook up new api to update record exporter status
Sage-Bionetworks/Bridge-Exporter pull request #33
Opened 2016-10-13 21:46 UTC by zaclinsage

update bridgeHelper to call new api to update record export status
    keep track of record ids in tsv file and update record exporter status by calling bridgehelper new method
    also add corresponding unit tests for above codes.

2016-10-14 22:41 UTC, alxdarksage requested changes
Some comments.

2016-10-14 22:41 UTC, alxdarksage commented on pom.xml
> +            <version>0.10.7</version>
I think this is now bumped to 0.11.1

2016-10-14 22:41 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/exporter/handler/HealthDataExportHandler.java
> +    }
Is this being injected by Spring? If so you can remove initialization to an instance. Is this not being injected? Then can you make a static final property of this class?

2016-10-14 22:41 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/exporter/handler/HealthDataExportHandler.java
> +            throw new BridgeExporterException("No record id in this tsv file.");
Are we sure this is an error condition? For example if no uploads occur in a study for an entire day or whatever the export period is, would it throw an exception where none is warranted?

2016-10-14 22:41 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/exporter/worker/TsvInfo.java
> +        this.recordIds = null;
I guess I would just this.recordIds = new ArrayList<>() right here, instead of requiring callers to pass it in.

2016-10-14 22:41 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/exporter/handler/SynapseExportHandlerTest.java
> +import static org.testng.Assert.*;
We usually import these individually. It's trivial, but I wouldn't break with this as the next checkin, there'll be a diff putting them all back again.

2016-10-14 22:41 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/exporter/handler/SynapseExportHandler.java
> +    }
I don't love these... do both ExportHandlers have to have all the same methods? Can these be removed somehow? These aren't declared in ExportHandler so it seems like it should be possible to remove them.

2016-10-14 22:44 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/exporter/handler/HealthDataExportHandler.java
> +    }
To add to this, HealthDataExportHandler already has the BridgeHelper through getManager().getBridgeHelper().

Also, don't override dependency injection setters. This leads to bad things happening.

2016-10-17 16:57 UTC, zaclinsage commented on src/test/java/org/sagebionetworks/bridge/exporter/handler/SynapseExportHandlerTest.java
> +import static org.testng.Assert.*;
oh i diddn't do that. the ide seems like to add it if i rely on all assert commands in this lib

2016-10-17 16:57 UTC, zaclinsage commented on src/main/java/org/sagebionetworks/bridge/exporter/handler/HealthDataExportHandler.java
> +            throw new BridgeExporterException("No record id in this tsv file.");
well yes i think the null is not permitted here. I changed the initialization to create a new arraylist instead of a null

2016-10-17 17:23 UTC, zaclinsage commented on src/test/java/org/sagebionetworks/bridge/exporter/handler/SynapseExportHandlerTest.java
> +import static org.testng.Assert.*;
i fixed it by changing ide settings

2016-10-17 17:23 UTC, zaclinsage commented on src/main/java/org/sagebionetworks/bridge/exporter/handler/HealthDataExportHandler.java
> +    }
delete my setter by using manager's one

2016-10-18 01:24 UTC, DwayneJengSage commented
Also, delete dump.rdb. This file is created by redis-server in the local directory and shouldn't be included in our codebase.

2016-10-18 01:28 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/exporter/handler/HealthDataExportHandler.java
> +    private BridgeHelper bridgeHelper = new BridgeHelper();
Remove unused bridgeHelper.

2016-10-18 01:28 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/exporter/worker/TsvInfo.java
> +        this.recordIds = recordIds;
recordIds is always an empty list, so instead of having the constructors create it, we should initialize it in the declaration above.

2016-10-18 01:28 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/exporter/worker/TsvInfo.java
> +    private List<String> recordIds;
Mark this as final. This ensures we aren't overwriting this somewhere.

2016-10-18 01:28 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/exporter/worker/TsvInfo.java
> +    }
For safety, I would wrap this in an ImmutableList.copyOf(this.recordIds). This ensures that whoever is calling this doesn't end up accidentally modifying it.

2016-10-18 01:28 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/exporter/handler/HealthDataExportHandler.java
> +            throw new BridgeExporterException("No record id in this tsv file.");
Since we're now always initializing recordIds to an empty list, this will never be null.

2016-10-18 02:32 UTC, DwayneJengSage requested changes

2016-10-18 02:32 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/exporter/handler/HealthDataExportHandler.java
> +import org.sagebionetworks.bridge.sdk.models.healthData.RecordExportStatusRequest;
Minor: Remove unused imports "SpringConfig" and "SignInCredentials". I believe by default, IntelliJ marks these as warnings. (Although they might have changed this.)

2016-10-18 02:32 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/exporter/helper/BridgeHelper.java
> +        setCredentials(credentials);
Don't do this. Spring is supposed to take care of credentials.

2016-10-18 02:32 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/exporter/helper/BridgeHelper.java
> +        });
List of record IDs may be larger than your batch size. You'll need to break down the list into batches and call Bridge in a loop, sleeping between each batch. (Most likely sleeping for 1 second between each batch.)

2016-10-18 02:32 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/exporter/handler/SynapseExportHandlerTest.java
> +        }
We should also verify that BridgeHelper.recordExportStatus() was called.

2016-10-18 02:32 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/exporter/helper/BridgeHelperTest.java
> +    ArgumentCaptor<RecordExportStatusRequest> requestArgumentCaptor = ArgumentCaptor.forClass(RecordExportStatusRequest.class);
It's not clear to me that TestNG creates a new test class instance before each test. You should initialize this in a @BeforeMethod instead.

2016-10-18 02:32 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/exporter/helper/BridgeHelperTest.java
> +        assertEquals(request.getRecordIds().get(0), TEST_RECORD_IDS.get(0));
You can actually just call equals() on lists.

2016-10-18 18:19 UTC, DwayneJengSage requested changes

2016-10-18 18:19 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/exporter/helper/BridgeHelper.java
> +                e.printStackTrace();
Minor: Instead of e.printStackTrace(), use LOG.warn(). This will ensure our output goes to the logs.

2016-10-18 18:19 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/exporter/helper/BridgeHelperTest.java
> +        request.getRecordIds().equals(TEST_RECORD_IDS);
You need an assert here.

2016-10-18 21:44 UTC, merged